Update to version 3.4.2. Remove cat from the Extcomm. Remove ${BASH_SOURCE} from the warn function. Adjust the indentation of all the case statements. Use the builtin IFS and read to save the Help and About menu's. Disable all shellcheck errors.

diff --git a/setx b/setx
--- a/setx
+++ b/setx
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 shopt -s extglob
 
@@ -6,14 +6,14 @@ shopt -s extglob
 #: Title           : setx                                                                      #
 #: Sypnosis        : setx [OPTION]... [FILE]                                                   #
 #: Date Created    : Tue May 31 15:59:31 PHT 2016 / Tue May 31 07:59:31 UTC 2016               #
-#: Last Edit       : Sat Sep  3 08:05:45 PHT 2016 / Sat Sep  3 00:05:45 UTC 2016               #
+#: Last Edit       : Mon Sep 19 16:23:13 PHT 2016 / Mon Sep 19 08:23:13 UTC 2016               #
 #: License         : Apache-2.0                                                                #
-#: Version         : 3.4.0                                                                     #
+#: Version         : 3.4.2                                                                     #
 #: Author          : Jason V. Ferrer '<jetchisel@opensuse.org>'                                #
 #: Description     : Insert/remove `Debug codes' in a file/script plus more.                   #
 #: Options         : -[achptrxX]                                                               #
 #: Home Page       : https://github.com/Jetchisel/setx                                         #
-#: ExtComm         : cat,ed,file                                                               #
+#: ExtComm         : ed,file                                                                   #
 # ============================================================================================ #
 
 # ******************************************************************************************** #
@@ -23,19 +23,23 @@ shopt -s extglob
 # ******************************************************************************************** #
 
 warn() {
-  printf '%s\n' "${BASH_SOURCE##*/}: $*"
+  printf '%s\n' "$@"
 }
 
 die() {
   local st=$?
   case $2 in
-    *[^0-9]*|'') :;;
-    *) st=$2;;
+    *[^0-9]*|'') :
+      ;;
+    *) st=$2
+      ;;
   esac
 
   case $st in
-    0) warn "$1" ;;
-    *) warn "$1" >&2;;
+    0) warn "$1"
+      ;;
+    *) warn "$1" >&2
+      ;;
   esac
 
   exit "$st"
@@ -48,7 +52,7 @@ die() {
 # ******************************************************************************************** #
 
 Missing=()
-ExtComm=(cat ed file)
+ExtComm=(ed file)
 MissingMessage="is either not installed or it is not in your PATH!"
 ExitMessage="Please install the following: "
 
@@ -67,20 +71,19 @@ done
 #                                                                                              #
 # ******************************************************************************************** #
 
-ShowHelp() {
-   cat <<EOF
+IFS= read -rd '' ShowHelp <<EOF
 
 Usage: ${BASH_SOURCE##*/} [OPTION]... [FILE]
 
 Options:
-  -h  --help     Show this help.
-  -a, --about    Show a brief info about ${BASH_SOURCE##*/}.
-  -c, --comment  Add a # in front of a line.
-  -r, --remove   Remove all the [keyword] code.
-  -x, --xtrace   Add \`set -x' code to the second line by default.
-  -X, --Xtrace   Add \`set -x' and a \`PS4' code at the second line. by default.
-  -p, --print    Print [keyword] code.
-  -t, --trap     Make the execution of the script line by line, defaults to the second line.
+-h  --help     Show this help.
+-a, --about    Show a brief info about ${BASH_SOURCE##*/}.
+-c, --comment  Add a # in front of a line.
+-r, --remove   Remove all the [keyword] code.
+-x, --xtrace   Add \`set -x' code to the second line by default.
+-X, --Xtrace   Add \`set -x' and a \`PS4' code at the second line. by default.
+-p, --print    Print [keyword] code.
+-t, --trap     Make the execution of the script line by line, defaults to the second line.
 
 Examples:
 
@@ -101,27 +104,25 @@ ${BASH_SOURCE##*/} -r [keyword] FILE    Remove all the [keyword] code if found i
 
 Keywords:
 
-  debug    All the debug codes \`set -x', \`set +x', and the \`trap'.
-  comment  All the lines that has been commented by adding a # in front.
-  tspace   All the lines that has trailing white space.
+debug    All the debug codes \`set -x', \`set +x', and the \`trap'.
+comment  All the lines that has been commented by adding a # in front.
+tspace   All the lines that has trailing white space.
 
 
 Caveat:
-  Inserting any code inside the case statement for example will surely
-  break its syntax and will add more bugs in the script in question.
+Inserting any code inside the case statement for example will surely
+break its syntax and will add more bugs in the script in question.
 EOF
-}
 
 # ******************************************************************************************** #
 #                                                                                              #
-#                        Function to print some info about the script.                         #
+#                                       The about menu.                                        #
 #                                                                                              #
 # ******************************************************************************************** #
 
-About() {
-   cat <<EOF
+IFS= read -rd '' About <<EOF
 
-                           setx
+                              setx
 
 A  bash  shell script  that  insert \`set [+-]x'  and a \`PS4' debug
 code or a trap to make the script  execute line by  line by  using
@@ -135,7 +136,7 @@ Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at
 
-    http://www.apache.org/licenses/LICENSE-2.0
+http://www.apache.org/licenses/LICENSE-2.0
 
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
@@ -143,7 +144,6 @@ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License
 EOF
-}
 
 # ******************************************************************************************** #
 #                                                                                              #
@@ -159,7 +159,9 @@ rb=$(tput setaf 1; printf '%s' "$b")
 setxcode='set -x #_S_E_T_X_#'
 commentcode="#(${BASH_SOURCE##*/})#"
 endsetxcode='set +x #_E_N_D_S_E_T_X_#'
+# shellcheck disable=2016
 ps4code='PS4='\''+($?) $BASH_SOURCE:$FUNCNAME:$LINENO:'\'' #_P_S_4_#'
+# shellcheck disable=2016
 trapcode='trap '\''(read -p "[$BASH_SOURCE:$LINENO] $BASH_COMMAND? ")'\'' DEBUG #_T_R_A_P_#'
 
 # ******************************************************************************************** #
@@ -190,50 +192,50 @@ while (($#)); do
   while [[ $1 = -?* ]]; do
     case $1 in
       -a|--about)
-          die "$(About)"
+        die "$About"
         ;;
       -c|--comment)
-         commentopts+=("$1") && ConflictArg "${commentopts[@]}"
-         comment=("${@:2:2}")
-         ((!${#comment[@]})) && die "$1 requires an argument!" 1
-         shift
-         ;;
+
+        comment=("${@:2:2}")
+        ((!${#comment[@]})) && die "$1 requires an argument!" 1
+        shift
+        ;;
       -h|--help)
-          die "$(ShowHelp)"
-         ;;
+        die "$ShowHelp"
+        ;;
       -p|--print)
-         printopts+=("$1") && ConflictArg "${printopts[@]}"
-         print=("${@:2:2}")
-         ((!${#print[@]})) && die "$1 requires an argument!" 1
-         shift
-         ;;
+        printopts+=("$1") && ConflictArg "${printopts[@]}"
+        print=("${@:2:2}")
+        ((!${#print[@]})) && die "$1 requires an argument!" 1
+        shift
+        ;;
       -t|--trap)
-         trapopts+=("$1") && ConflictArg "${trapopts[@]}"
-         trap=("${@:2:2}")
-         ((!${#trap[@]})) && die "$1 requires an argument!" 1
-         shift
-         ;;
+        trapopts+=("$1") && ConflictArg "${trapopts[@]}"
+        trap=("${@:2:2}")
+        ((!${#trap[@]})) && die "$1 requires an argument!" 1
+        shift
+        ;;
       -r|--remove)
-         removeopts+=("$1") && ConflictArg "${removeopts[@]}"
-         remove=("${@:2:2}")
-         ((!${#remove[@]})) && die "$1 requires an argument!" 1
-         shift
+        removeopts+=("$1") && ConflictArg "${removeopts[@]}"
+        remove=("${@:2:2}")
+        ((!${#remove[@]})) && die "$1 requires an argument!" 1
+        shift
         ;;
       -x|--xtrace)
-         xtraceopts+=("$1") && ConflictArg "${xtraceopts[@]}"
-         xtrace=("${@:2:2}")
-         ((!${#xtrace[@]})) && die "$1 requires an argument!" 1
-         shift
+        xtraceopts+=("$1") && ConflictArg "${xtraceopts[@]}"
+        xtrace=("${@:2:2}")
+        ((!${#xtrace[@]})) && die "$1 requires an argument!" 1
+        shift
         ;;
       -X|--Xtrace)
-         Xtraceopts+=("$1") && ConflictArg "${Xtraceopts[@]}"
-         Xtrace=("${@:2:2}")
-         ((!${#Xtrace[@]})) && die "$1 requires an argument!" 1
-         shift
+        Xtraceopts+=("$1") && ConflictArg "${Xtraceopts[@]}"
+        Xtrace=("${@:2:2}")
+        ((!${#Xtrace[@]})) && die "$1 requires an argument!" 1
+        shift
         ;;
-       *)
-         die "Invalid option \`$*'" 1
-       ;;
+      *)
+        die "Invalid option \`$*'" 1
+        ;;
     esac
   done
   shift
@@ -382,7 +384,7 @@ fi
 for files in "$commentFiLe" "$trapFiLe" "$printFiLe" "$xtraceFiLe" "$XtraceFiLe" "$removeFiLe"; do
   [[ $files ]] && FiLe=$files
 done
-[[ ! $FiLe ]] && die "$(ShowHelp)" 1
+[[ ! $FiLe ]] && die "$ShowHelp" 1
 
 # ******************************************************************************************** #
 #                                                                                              #
@@ -432,11 +434,11 @@ WholeLineofFiLe() {
 # ******************************************************************************************** #
 
 IsetXcode=$(
-  while IFS= read -r line; do
-    if [[ ${line#*:} = "$setxcode"* ]]; then
-      printf '%s\n' "$line"
-    fi
-  done < <(WholeLineofFiLe)
+while IFS= read -r line; do
+  if [[ ${line#*:} = "$setxcode"* ]]; then
+    printf '%s\n' "$line"
+  fi
+done < <(WholeLineofFiLe)
 )
 
 # ******************************************************************************************** #
@@ -446,11 +448,11 @@ IsetXcode=$(
 # ******************************************************************************************** #
 
 IsetEndcode=$(
-  while IFS= read -r line; do
-    if [[ ${line#*:} = "$endsetxcode"* ]]; then
-      printf '%s\n' "$line"
-    fi
-  done < <(WholeLineofFiLe)
+while IFS= read -r line; do
+  if [[ ${line#*:} = "$endsetxcode"* ]]; then
+    printf '%s\n' "$line"
+  fi
+done < <(WholeLineofFiLe)
 )
 
 # ******************************************************************************************** #
@@ -460,11 +462,11 @@ IsetEndcode=$(
 # ******************************************************************************************** #
 
 IstrapCode=$(
-  while IFS= read -r line; do
-    if [[ ${line#*:} = "$trapcode"* ]]; then
-      printf '%s\n' "$line"
-    fi
-  done < <(WholeLineofFiLe)
+while IFS= read -r line; do
+  if [[ ${line#*:} = "$trapcode"* ]]; then
+    printf '%s\n' "$line"
+  fi
+done < <(WholeLineofFiLe)
 )
 
 # ******************************************************************************************** #
@@ -497,9 +499,9 @@ Insertx() {
   fi
 
   if [[ $EndLine ]]; then
-     if [[ $IsetEndcode ]]; then
-       die "$FiLe has ${endsetxcode%+( )*} code at line ${IsetEndcode%%:*}" 1
-     elif [[ $IsetXcode ]]; then
+    if [[ $IsetEndcode ]]; then
+      die "$FiLe has ${endsetxcode%+( )*} code at line ${IsetEndcode%%:*}" 1
+    elif [[ $IsetXcode ]]; then
       if [[ $EndLine -le ${IsetXcode%%:*} ]]; then
         die "${setxcode%+( )*} before ${endsetxcode%+( )*}"
       fi
@@ -516,6 +518,7 @@ Insertx() {
     fi
   elif [[ $StartLine ]]; then
     if [[ $TotalLines -eq 1 && $StartLine -eq 1 ]]; then
+      # shellcheck disable=2016
       printf '%s\n' H '$a' "$setxcode" . w q | ed -s "$FiLe"
       warn "Inserted $rb${setxcode%+( )*}$reset at the last line of $FiLe."
     elif [[ $TotalLines -gt 1 && $StartLine -eq 1 ]]; then
@@ -527,6 +530,7 @@ Insertx() {
     fi
   elif [[ $EndLine ]]; then
     if [[ $TotalLines -eq 1 && $EndLine -eq 1 ]]; then
+      # shellcheck disable=2016
       printf '%s\n' H '$a' "$endsetxcode" . w q | ed -s "$FiLe"
       warn "Inserted $rb${endsetxcode%+( )*}$reset at the last line of $FiLe."
     elif [[ $TotalLines -gt 1 && $EndLine -eq 1 ]]; then
@@ -589,6 +593,7 @@ InsertX() {
     fi
   elif [[ $StartLine ]]; then
     if [[ $TotalLines -eq 1 && $StartLine -eq 1 ]]; then
+      # shellcheck disable=2016
       printf '%s\n' H '$a' "${SetxCode[@]}" . w q | ed -s "$FiLe"
       warn "Inserted $rb${ps4code%+( )*}$reset,$rb${setxcode%+( )*}$reset at the last line of $FiLe."
     elif [[ $TotalLines -gt 1 && $StartLine -eq 1 ]]; then
@@ -600,6 +605,7 @@ InsertX() {
     fi
   elif [[ $EndLine ]]; then
     if [[ $TotalLines -eq 1 && $EndLine -eq 1 ]]; then
+      # shellcheck disable=2016
       printf '%s\n' H '$a' "$endsetxcode" . w q | ed -s "$FiLe"
       warn "Inserted $rb${endsetxcode%+( )*}$reset at the last line of $FiLe."
     elif [[ $TotalLines -gt 1 && $EndLine -eq 1 ]]; then
@@ -627,6 +633,7 @@ InsertTrap() {
     if [[ $StartLine -gt $TotalLines ]]; then
       die "$rb$StartLine$reset is more than $rb$TotalLines$reset line(s) of $FiLe"
     elif [[ $TotalLines -eq 1 && $StartLine -eq 1 ]]; then
+      # shellcheck disable=2016
       printf '%s\n' H '$a' "$trapcode" . w q | ed -s "$FiLe"
       warn "Inserted \`$rb${trapcode%+( )*}$reset' at the last line of $FiLe."
     elif [[ $TotalLines -gt 1 && $StartLine -eq 1 ]]; then
@@ -829,7 +836,7 @@ Pdebug() {
 # ******************************************************************************************** #
 
 RemoveInsertX() {
-   printf '%s\n' H 'g/^set.*-x.*#_S_E_T_X_#$/d' w q | ed -s "$FiLe"
+  printf '%s\n' H 'g/^set.*-x.*#_S_E_T_X_#$/d' w q | ed -s "$FiLe"
 }
 
 # ******************************************************************************************** #
@@ -839,7 +846,7 @@ RemoveInsertX() {
 # ******************************************************************************************** #
 
 RemoveEndXcode() {
-   printf '%s\n' 'g/^set.*+x.*#_E_N_D_S_E_T_X_#$/d' w q | ed -s "$FiLe"
+  printf '%s\n' 'g/^set.*+x.*#_E_N_D_S_E_T_X_#$/d' w q | ed -s "$FiLe"
 }
 
 # ******************************************************************************************** #
@@ -849,7 +856,7 @@ RemoveEndXcode() {
 # ******************************************************************************************** #
 
 RemoveInsertPs4() {
-   printf '%s\n' H 'g/^PS4=.*#_P_S_4_#$/d' w q | ed -s "$FiLe"
+  printf '%s\n' H 'g/^PS4=.*#_P_S_4_#$/d' w q | ed -s "$FiLe"
 }
 
 # ******************************************************************************************** #
@@ -889,11 +896,21 @@ RemoveDebug() {
 
 Remove() {
   case $RemoveArg in
-    cr) RemoveCarriage;;
-    debug) RemoveDebug;;
-    comment) RemoveComment;;
-    tspace) RemoveTspace;;
-    *) die "Invalid argument \`$RemoveArg'!";;
+    cr)
+      RemoveCarriage
+      ;;
+    debug)
+      RemoveDebug
+      ;;
+    comment)
+      RemoveComment
+      ;;
+    tspace)
+      RemoveTspace
+      ;;
+    *)
+      die "Invalid argument \`$RemoveArg'!"
+      ;;
   esac
 }
 
@@ -905,11 +922,20 @@ Remove() {
 
 Print() {
   case $printArg in
-    cr) Pcarriage;;
-    comment) Pcomment ;;
-    debug) Pdebug ;;
-    tspace) Ptspace ;;
-    *) die "Invalid argument \`$printArg'!";;
+    cr) Pcarriage
+      ;;
+    comment)
+      Pcomment
+      ;;
+    debug)
+      Pdebug
+      ;;
+    tspace)
+      Ptspace
+      ;;
+    *)
+      die "Invalid argument \`$printArg'!"
+      ;;
   esac
 }
 
@@ -926,7 +952,7 @@ elif [[ $xtraceFiLe ]]; then
 elif [[ $commentFiLe ]]; then
   Comment
 elif [[ $trapFiLe ]]; then
- InsertTrap
+  InsertTrap
 elif [[ $printFiLe ]]; then
   Print
 elif [[ $removeFiLe ]]; then
